server:
  port: 7779
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_rbac_system?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: com/dylan/rbac/dao/xml/**/*.xml
logging:
  level:
    com.dylan.rbac: debug
